trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

steps:
  - script: npm i
    displayName: "Install package"
  - script: vsce package
    displayName: "Package"
  - script: vsce publish -p $(PAT)
    displayName: "Publish"
